Repository SAP/python-pyodata, pull requests merged in 2022-01, with the labels that each got.

#192 Drop support for Python 3.6
  .travis.yml
  CHANGELOG.md
  README.md
  requirements.txt
  setup.py
Labels: chore

#184 model: fix timezone handling for Edm.DateTimeOffset
  CHANGELOG.md
  pyodata/v2/model.py
  tests/conftest.py
  tests/metadata.xml
  tests/test_model_v2.py
  tests/test_service_v2.py
Labels: bug

#189 service: Support null (#79)
  CHANGELOG.md
  docs/usage/initialization.rst
  pyodata/client.py
  pyodata/v2/model.py
  pyodata/v2/service.py
  tests/test_service_v2.py
Labels: enhancement
